web:
  mode: "debug" # debug release test
  port: 8000
database:
  driver: "mysql"
  address: "127.0.0.1"
  port: 3306
  db: "task_manager"
  dbUser: "root"
  dbPassword: "Dc@123"
redis:
  address: "127.0.0.1:6379" # 集群以逗号隔开
  isCluster: false
  usePassword: true
  password: "Dc!123"
  db: 1 # 默认DB
  taskDB: 2 # 任务队列DB,不填默认为 db
log:
  debugMode: true
  logLevel: "info"  # "panic", "fatal", "error", "warn", "info", "debug"
  logPath: "/tmp"
email:
  mailHost: "smtp.163.com"
  mailPort: 25
  userName: "13637235955@163.com"
  password: "CKXQRZXRXTKVDMJL"  # 授权码

# id_rsa.pub
secrets: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCswRfXSgkc7vgNnrWwcd3mmhFuxLRQj62Co3ObfrUTgHuDp/s9YgVWuD75D0bDKHb8PviZ2/vlGTQwyWIJpRjU51CQY3OVEzFtrxSKjdiUOVdlvELLS645Y+tqrU/bhzwk8Z5ntQcoff+z/ZFNtjYBHjrJ+tPXVzW+l7zdRcmVCrW5HjZPRAjlr0GzfuBSK62EDtHmATZRTxRvTr+M6nMhDe70rVp3u4ede4CeejPYdiHbrjn0WYndOfWzcV8Seg8YHyt2cZ9lhF57e79yWxxcyiH1wbcgBTvLytIeh5eVFOjR0HtKwfZEBf8JY87+vc0Yz6FM1to4dvu3bsze9FrN daicheng@daichengdeMacBook-Pro.local"